/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosIndexRouteImport } from './routes/servicios/index'
import { Route as ServiciosCategoriaIdRouteImport } from './routes/servicios/$categoriaId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedReservarRouteImport } from './routes/_authenticated/reservar'
import { Route as AuthenticatedPedidoPersonalizadoRouteImport } from './routes/_authenticated/pedido-personalizado'
import { Route as AuthenticatedMisReservasRouteImport } from './routes/_authenticated/mis-reservas'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminServiciosRouteImport } from './routes/_authenticated/admin/servicios'
import { Route as AuthenticatedAdminPeluquerosRouteImport } from './routes/_authenticated/admin/peluqueros'
import { Route as AuthenticatedAdminCobrosRouteImport } from './routes/_authenticated/admin/cobros'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin/clientes'
import { Route as AuthenticatedAdminAgendaRouteImport } from './routes/_authenticated/admin/agenda'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosCategoriaIdRoute = ServiciosCategoriaIdRouteImport.update({
  id: '/servicios/$categoriaId',
  path: '/servicios/$categoriaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedReservarRoute = AuthenticatedReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidoPersonalizadoRoute =
  AuthenticatedPedidoPersonalizadoRouteImport.update({
    id: '/pedido-personalizado',
    path: '/pedido-personalizado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMisReservasRoute =
  AuthenticatedMisReservasRouteImport.update({
    id: '/mis-reservas',
    path: '/mis-reservas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminServiciosRoute =
  AuthenticatedAdminServiciosRouteImport.update({
    id: '/servicios',
    path: '/servicios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPeluquerosRoute =
  AuthenticatedAdminPeluquerosRouteImport.update({
    id: '/peluqueros',
    path: '/peluqueros',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCobrosRoute =
  AuthenticatedAdminCobrosRouteImport.update({
    id: '/cobros',
    path: '/cobros',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAgendaRoute =
  AuthenticatedAdminAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/mis-reservas': typeof AuthenticatedMisReservasRoute
  '/pedido-personalizado': typeof AuthenticatedPedidoPersonalizadoRoute
  '/reservar': typeof AuthenticatedReservarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/servicios/$categoriaId': typeof ServiciosCategoriaIdRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cobros': typeof AuthenticatedAdminCobrosRoute
  '/admin/peluqueros': typeof AuthenticatedAdminPeluquerosRoute
  '/admin/servicios': typeof AuthenticatedAdminServiciosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/mis-reservas': typeof AuthenticatedMisReservasRoute
  '/pedido-personalizado': typeof AuthenticatedPedidoPersonalizadoRoute
  '/reservar': typeof AuthenticatedReservarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/servicios/$categoriaId': typeof ServiciosCategoriaIdRoute
  '/servicios': typeof ServiciosIndexRoute
  '/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/cobros': typeof AuthenticatedAdminCobrosRoute
  '/admin/peluqueros': typeof AuthenticatedAdminPeluquerosRoute
  '/admin/servicios': typeof AuthenticatedAdminServiciosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/mis-reservas': typeof AuthenticatedMisReservasRoute
  '/_authenticated/pedido-personalizado': typeof AuthenticatedPedidoPersonalizadoRoute
  '/_authenticated/reservar': typeof AuthenticatedReservarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/servicios/$categoriaId': typeof ServiciosCategoriaIdRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/_authenticated/admin/agenda': typeof AuthenticatedAdminAgendaRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/cobros': typeof AuthenticatedAdminCobrosRoute
  '/_authenticated/admin/peluqueros': typeof AuthenticatedAdminPeluquerosRoute
  '/_authenticated/admin/servicios': typeof AuthenticatedAdminServiciosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/mis-reservas'
    | '/pedido-personalizado'
    | '/reservar'
    | '/auth/callback'
    | '/servicios/$categoriaId'
    | '/servicios/'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/cobros'
    | '/admin/peluqueros'
    | '/admin/servicios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/mis-reservas'
    | '/pedido-personalizado'
    | '/reservar'
    | '/auth/callback'
    | '/servicios/$categoriaId'
    | '/servicios'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/cobros'
    | '/admin/peluqueros'
    | '/admin/servicios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/mis-reservas'
    | '/_authenticated/pedido-personalizado'
    | '/_authenticated/reservar'
    | '/auth/callback'
    | '/servicios/$categoriaId'
    | '/servicios/'
    | '/_authenticated/admin/agenda'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/cobros'
    | '/_authenticated/admin/peluqueros'
    | '/_authenticated/admin/servicios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ServiciosCategoriaIdRoute: typeof ServiciosCategoriaIdRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$categoriaId': {
      id: '/servicios/$categoriaId'
      path: '/servicios/$categoriaId'
      fullPath: '/servicios/$categoriaId'
      preLoaderRoute: typeof ServiciosCategoriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/reservar': {
      id: '/_authenticated/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof AuthenticatedReservarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedido-personalizado': {
      id: '/_authenticated/pedido-personalizado'
      path: '/pedido-personalizado'
      fullPath: '/pedido-personalizado'
      preLoaderRoute: typeof AuthenticatedPedidoPersonalizadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mis-reservas': {
      id: '/_authenticated/mis-reservas'
      path: '/mis-reservas'
      fullPath: '/mis-reservas'
      preLoaderRoute: typeof AuthenticatedMisReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/servicios': {
      id: '/_authenticated/admin/servicios'
      path: '/servicios'
      fullPath: '/admin/servicios'
      preLoaderRoute: typeof AuthenticatedAdminServiciosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/peluqueros': {
      id: '/_authenticated/admin/peluqueros'
      path: '/peluqueros'
      fullPath: '/admin/peluqueros'
      preLoaderRoute: typeof AuthenticatedAdminPeluquerosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cobros': {
      id: '/_authenticated/admin/cobros'
      path: '/cobros'
      fullPath: '/admin/cobros'
      preLoaderRoute: typeof AuthenticatedAdminCobrosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/agenda': {
      id: '/_authenticated/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AuthenticatedAdminAgendaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAgendaRoute: typeof AuthenticatedAdminAgendaRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminCobrosRoute: typeof AuthenticatedAdminCobrosRoute
  AuthenticatedAdminPeluquerosRoute: typeof AuthenticatedAdminPeluquerosRoute
  AuthenticatedAdminServiciosRoute: typeof AuthenticatedAdminServiciosRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAgendaRoute: AuthenticatedAdminAgendaRoute,
    AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
    AuthenticatedAdminCobrosRoute: AuthenticatedAdminCobrosRoute,
    AuthenticatedAdminPeluquerosRoute: AuthenticatedAdminPeluquerosRoute,
    AuthenticatedAdminServiciosRoute: AuthenticatedAdminServiciosRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedMisReservasRoute: typeof AuthenticatedMisReservasRoute
  AuthenticatedPedidoPersonalizadoRoute: typeof AuthenticatedPedidoPersonalizadoRoute
  AuthenticatedReservarRoute: typeof AuthenticatedReservarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedMisReservasRoute: AuthenticatedMisReservasRoute,
  AuthenticatedPedidoPersonalizadoRoute: AuthenticatedPedidoPersonalizadoRoute,
  AuthenticatedReservarRoute: AuthenticatedReservarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ServiciosCategoriaIdRoute: ServiciosCategoriaIdRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
